default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: authors_and_pubs_apis_development
  username: postgres
  password: 123456

test:
  <<: *default
  database: authors_and_pubs_apis_test
  username: postgres
  password: 123456
production:
  <<: *default
  database: authors_and_pubs_apis_production
  username: authors_and_pubs_apis
  password: <%= ENV['AUTHORS_AND_PUBS_APIS_DATABASE_PASSWORD'] %>


